### ISSUE TITLE
Manifest media type is not updated after syncing the container repository.

### ISSUE THREAD

**Issue by hao-yu** [pulp/pulp_container#1189] opened 2022-12-20 05:02 UTC
I synced a "rhosp-rhel8/openstack-cinder-backup" repository a few months ago and it has one OCI image manifest.
```
pulpcore=# select * from container_manifest where digest = 'sha256:41626b0aa129679bb0b4f4461d1162bc94c89d52c73c7cd4b976ab73492a9c28';
            content_ptr_id            |                                 digest                                  | schema_version |                 media_type                 |            config_blob_id            
--------------------------------------+-------------------------------------------------------------------------+----------------+--------------------------------------------+--------------------------------------
 4d221b64-9056-4522-91d7-603a9ffb6d50 | sha256:41626b0aa129679bb0b4f4461d1162bc94c89d52c73c7cd4b976ab73492a9c28 |              1 | application/vnd.oci.image.manifest.v1+json | e7c6771d-dfd1-4fdf-8ecb-541b81d2fdc2
```

But somehow the image manifest is now corrected to Manifest V2 schema 2 image. This is confirmed by creating a new repository and sync it with the latest "rhosp-rhel8/openstack-cinder-backup" upstream repository using another Satellite.
```
pulpcore=# select * from container_manifest where digest = 'sha256:41626b0aa129679bb0b4f4461d1162bc94c89d52c73c7cd4b976ab73492a9c28';
            content_ptr_id            |                                 digest                                  | schema_version |                      media_type                      |            config_blob_id
            
--------------------------------------+-------------------------------------------------------------------------+----------------+------------------------------------------------------+--------------------------
------------
 7ad824d4-fde3-4cd3-8f63-495558580ca3 | sha256:41626b0aa129679bb0b4f4461d1162bc94c89d52c73c7cd4b976ab73492a9c28 |              2 | application/vnd.docker.distribution.manifest.v2+json | 28fcb6e3-57c2-432b-a82c-a
4980a7ed1eb
(1 row)
```

After re-syncing the "rhosp-rhel8/openstack-cinder-backup" repository on the original Satellite, the media type remain the same and not reflecting the upstream repository.

This will cause the Satellite Capsule sync to fail with 404 not found error because Katello didn't support the OC image manifest format before this fix https://github.com/Katello/katello/pull/10332 . This fix has not yet been applied to any downstream release

**Comment by ipanova** [comment] 2023-01-03 11:38
Thank you for the report.
Please provide according pulp versions. I assume there are involved 2 different versions ( one which was in the original sync and second version on the re-sync)

**Comment by hao-yu** [comment] 2023-01-04 07:30
The original sync and re-sync are on the same Satellite and Pulp version. As described above, I synced the container repo some time ago, and then I re-sync it recently but the image manifest media type is still not reflecting upstream.
~~~
tfm-pulpcore-python3-pulpcore-3.16.14-1.el7pc.noarch
tfm-pulpcore-python3-pulp-container-2.9.2-1.el7pc.noarch
~~~

When using another Satellite  to sync the container repo from scratch, the image manifest type is correct. I think this proved that the media type has been corrected upstream (although the used pulp version is newer).
~~~
python39-pulpcore-3.18.10-1.el8pc.noarch
python39-pulp-container-2.10.9-1.el8pc.noarch
~~~

**Comment by ipanova** [comment] 2023-01-04 12:27
@hao-yu while you are at it, can you please share the manifest.json output from both satellites.
I have determined that this is an image manifest that is part of a manifest list. Please share the manifest.json of the list too.
you can find it this way
```python

In [9]: ManifestListManifest.objects.filter(manifest_list_id__digest='sha256:41626b0aa129679bb0b4f4461d1162bc94c89d52c73c7cd4b976ab73492a9c28')
Out[9]: <QuerySet [<ManifestListManifest: ManifestListManifest object (86)>]>

In [10]: ManifestListManifest.objects.filter(manifest_list_id__digest='sha256:41626b0aa129679bb0b4f4461d1162bc94c89d52c73c7cd4b976ab73492a9c28')[0].image_manifest.media_type
Out[10]: 'application/vnd.docker.distribution.manifest.list.v2+json'

In [11]: ManifestListManifest.objects.filter(manifest_list_id__digest='sha256:41626b0aa129679bb0b4f4461d1162bc94c89d52c73c7cd4b976ab73492a9c28')[0].image_manifest.digest
Out[11]: 'sha256:352d306eb0c610f92a395440d68b975183982b3674f238519d3856e069791eca'

```

If the data was corrected upstream,correctly it should lead to the digest change of the manifest payload, whether this is a manifest list or image manifest.

**Comment by ipanova** [comment] 2023-01-04 12:41
What really surprised me is the combination of `schema_version 1` and media_type `application/vnd.oci.image.manifest.v1+json`

If you look at the code and ctrl+f for `schema_version` you will see that we directly take this information from the manifest payload, except for the this logical evaluation https://github.com/pulp/pulp_container/blob/2.9/pulp_container/app/tasks/sync_stages.py#L304 where we look at the media_type specified on the manifest list and determine the schema. Which in this case claims to be `application/vnd.oci.image.manifest.v1+json` meaning it would evaluate to 2. Makes no sense.

This thinking leads me to the conclusion( to be confirmed because I do not have at hand the history of the manifests) that the payload was indeed changed, without recalculation of the new manifest digest.

**Comment by hao-yu** [comment] 2023-01-05 03:15
@ipanova: The `schema_version` is indeed should be 2. I checked my query history in psql and I found that I manually updated it to '1' when I was doing some troubleshooting. However, i couldn't find anything in the history that I updated/touched the `media_type`(Maybe I did but the query history just don't cover long enough for me to track it).  If I didn't touch the `media_type`, it might still be possible that it has been updated without recalculating the digest upstream.

Since I am unable to confirm the integrity of the data in my database, I think we can close this issue until I can find a new evidence if it happens again. Is that OK for you? and I am so sorry about wasting your time looking into this issue.

**Comment by ipanova** [comment] 2023-01-05 10:44
@hao-yu you can still fetch the json file from the filesystem and compare those(between 2 satellites to see if they were changed upstream). We do not manipulate with its data, we save it as it comes from the upstream. 

This how you can find its storage path which is usually in var/lib/pulp/media/
```
manifest._artifacts.all()[0].file
Out[14]: <FieldFile: artifact/d4/856d10d6dc4fa25e41047f7c9abebef515193a361446bba13cda8550f04213>
```
I am fine closing this issue until we have a more reliable reproducer :+1:

**Closed** 2023-01-06 15:25 UTC
Labels: Issue, prio-list
