### ISSUE TITLE
Problem with jsonchema dependency on pulp-container 2.14

### ISSUE THREAD

**Issue by Odilhao** [pulp/pulp_container#1083] opened 2022-09-28 15:53 UTC
**Version**

Pulpcore 3.21
pulp_container 2.14

**Describe the bug**
The jsonschema version required by pulp_container conflicts with the version required by pulp-ansible

pulp-container requires ~=4.4
Pulp-ansible requires >=4.9,<4.10

This also conflicts with pulp-rpm that requires jsonschema~=4.6

**To Reproduce**
I'm branching the rpm packages for 3.21, it's not reproducible yet.

**Expected behavior**
All packages to have at least the same jsonchema version as dependency or having a more flexible dependency requirement.

**Additional context**

https://github.com/pulp/pulp_container/blob/2.14.0/requirements.txt#L6
https://github.com/pulp/pulp_rpm/blob/3.18.3/requirements.txt#L3
https://github.com/pulp/pulp_ansible/blob/0.15.0/requirements.txt#L4

**Comment by lubosmj** [comment] 2022-09-29 09:05
This is a duplicate of https://github.com/pulp/pulp_container/issues/772.

**Comment by fao89** [comment] 2022-10-03 11:03
> This is a duplicate of #772.

not duplicate, it happened again!

**Comment by ipanova** [comment] 2022-10-03 11:14
@Odilhao I see the discrepancy you're pointing out, however best what we can do is write guidelines on how to declare dependencies https://github.com/pulp/pulpcore/blob/main/docs/plugins/plugin-writer/concepts/index.rst#declaring-dependencies . Some plugins are out of our control so we cannot ensure every plugin uses same dep.version.
Based on what you have reported the 4.9 dependency requirement should be satisfied by all 3 plugins where:
pulp-container requires ~=4.4 translates to anything >=4.4,<5
pulp-ansible requires >=4.9,<4.10
pulp-rpm that requires jsonschema~=4.6 ranslates to anything >=4.6,<5

Do you see a different behavior?

**Comment by Odilhao** [comment] 2022-10-03 11:19
> @Odilhao I see the discrepancy you're pointing out, however best what we can do is write guidelines on how to declare dependencies https://github.com/pulp/pulpcore/blob/main/docs/plugins/plugin-writer/concepts/index.rst#declaring-dependencies . Some plugins are out of our control so we cannot ensure every plugin uses same dep.version.
> 
> Based on what you have reported the 4.9 dependency requirement should be satisfied by all 3 plugins where:
> 
> ```
> 
> pulp-container requires ~=4.4 translates to anything >=4.4,<5
> 
> pulp-ansible requires >=4.9,<4.10
> 
> pulp-rpm requires jsonschema~=4.6 ranslates to anything >=4.6,<5
> 
> ```
> 
> Do you see a different behavior?
> 
> 

This is the behavior that I expect, I already did a PR last week to publish the rpms.

https://github.com/theforeman/pulpcore-packaging/pull/587

I saw that we are pining cryptography, can we keep that one without a version pin? AFAIK we ship one old stable version that don't need rust, it's 3.x I think.

**Comment by ipanova** [comment] 2022-10-03 11:55
Have you seen these changes?
https://github.com/pulp/pulpcore/commit/eb0f4fe9bdd73429f60665a06bae45c427ad888
https://github.com/pulp/pulpcore/blob/main/docs/plugins/plugin-writer/concepts/index.rst#declaring-dependencies

Given that you opened this issue, that is your expectation of the fix? Based on my comment - I do not see any current problem with dependencies.

**Comment by ipanova** [comment] 2022-10-07 13:51
I am unsure what is required to be done in this request, unassigning.

**Comment by dkliban** [comment] 2022-10-07 13:51
pulp_container needs to stop using ~= in the requirements.txt.

**Comment by ipanova** [comment] 2022-10-07 14:22
In the next release we will switch to `>=x,<=y` format @Odilhao

**Comment by ipanova** [comment] 2022-10-24 11:38
2.14.2 is out

**Closed by ipanova** 2022-10-24 11:38 UTC
Labels: Issue, prio-list

**Comment by tjmullicani** [comment] 2022-11-23 15:51
[pulp_ansible](https://github.com/pulp/pulp_ansible/blob/853e209f8900444fb8735ac10df17b4100a42682/requirements.txt#L4) has been updated to use jsonschema 4.17 (required by ansible-lint v6.8.7, which is a dependency for galaxy_importer). The current pulp_container setting of <4.17 will cause errors when installing together with pulp_ansible.

**Comment by ipanova** [comment] 2022-11-23 16:54
@tjmullicani  thanks for pointing out. the jsonschema dep was updated on the main brain of pulp_ansible, we will make sure that main brain of pulp_container includes  3.17
